config/routes.rb
Rails.application.routes.draw do
  resources :cards
  get "paiementsucces", to: "order#paiementsuccess"
  get 'monpaiement', to: "order#monpaiement"
  get 'okorder', to: "order#okorder"
  get 'delete/:id', to: "order#deletemyaction"
  get 'order', to: "order#myorder"
  get 'order/myorder'
  get "inscriptions/success", to: "inscriptions#success", as: :moninscription
  get 'achats/cours'
  devise_scope :user do 
    patch "/okorder", to: "users/registrations#update", as: :editercollectifs_post
    post "/inscription-:mytype", to: "users/registrations#create", as: :inscriptioncollectifs_post
  end
  devise_for :users, controllers: { registrations: 'users/registrations',sessions: 'users/sessions'  }
  resources :courses
  get 'achats-cours-:mytype', to:"achats#cours", as: :achatscours
  get 'achats-cours-:mytype/:id/ajouteraupanier', to:"achats#show", as: :achatscourspanier
  get 'achats-cours-:mytype/:id/add', to:"achats#add", as: :achatsadd
  get 'inscriptions/index'
  resources :courses
  resources :webbillets
  get "/forminscriptions", to: "inscription#form", as: :inscriptionform
  get "/inscription-individuels", to: "inscriptions#individuels", as: :inscriptionindividuels
  get "/inscription-collectifs", to: "inscriptions#collectifs", as: :inscriptioncollectifs

  get "/cours-collectifs-de-:name", to: "courses#show", as: :noscourscollectifsde
  get "/cours-individuels-de-:name", to: "courses#show", as: :noscoursindividuelsde
  get "/nos-cours-:type", to: "courses#index"
  #get 'ifdm/index'
  #get 'contact/index'
  #get 'internships/index'
  #get 'courses/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "ifdm#index"
  get "ifdm", to: "ifdm#index"
  get "nos-cours-individuels", to: "courses#individual", as: :coursindividuel
  get "nos-cours-collectifs", to: "courses#group", as: :courscollectif
  get "nos-cours-:type", to: "courses#index", as: :allcourses
  get "nos-stages", to: "internships#index"
  get "nos-evenements", to: "events#index"
  get "contact-2", to: "contact#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
belongs_to :payment
belongs_to :echeance, optional: true
before_save :mygmt
after_validation :addmyerror
def mypaymentcreated
j=self.gmt >= 0 ? "+" : ""
j<<self.gmt.to_s
(self.created_at+self.gmt.hours).to_datetime.change(offset: j)
end
def mygmt
self.gmt=Time.now.getlocal.strftime("%:z").to_i
end
def addmyerror
if self.payment.cards.length >= self.payment.option.to_i
self.errors.add(:myerror,"vous avez payé toute les échéances")
end
    if self.payment.echeancepassenonpayes.length > 0
self.errors.add(:myerror,"vous avez râté des échéances.contactez l'école")
 
   end
    if self.payment.echeancefuturnonpayes.length == 0
self.errors.add(:myerror,"vous avez payé toute les échéances")

    end
end
def mycardnumber
d=nb
d[0..-4]="x" * d[0..-4].length
d
end
end

app/models/collective.rb
class Collective < Course
end

app/models/course.rb
class Course < ApplicationRecord
 has_and_belongs_to_many :users, :join_table => :userhascourses
  attr_accessor :quantite
 include ActionView::Helpers::SanitizeHelper
  def self.mycourse
   all.select("courses.*, row_number() over(order by courses.id) as rownum").group(:id)
  end
 def mytitle 
   if Course.where(type:self.type,name: self.name).length > 1
   strip_tags(self.description).split("\n")[0]
   else
    name.titleize
   end
 end
 def name
  read_attribute(:name)
  end
 def name=(x)
  write_attribute(:name,x.gsub("COURS COLLECTIFS DE ","").gsub("COURS INDIVIDUELS DE ",""))
  end
def image=(uploaded_io)
  File.open(Rails.root.join('public','uploads',uploaded_io.original_filename),'wb') do |file|
    file.write(uploaded_io.read)
  end
  write_attribute(:image, uploaded_io.original_filename)
rescue
  write_attribute(:image, uploaded_io)
end
def image 
  read_attribute(:image)
end
def icon=(uploaded_io)
  File.open(Rails.root.join('public','uploads',uploaded_io.original_filename),'wb') do |file|
    file.write(uploaded_io.read)
  end
  write_attribute(:icon, uploaded_io.original_filename)
rescue
  write_attribute(:icon, uploaded_io)
end
def icon
  read_attribute(:icon)
end
end

app/models/echeance.rb
class Echeance < ApplicationRecord
belongs_to :payment
has_one :card
validates_uniqueness_of :payment_id, scope: :date
def self.mesecheances
where("date >= ?",Date.today)
end
end

app/models/level.rb
class Level < ApplicationRecord
end

app/models/payment.rb
class Payment < ApplicationRecord
has_many :echeances
has_many :cards
belongs_to :user
def monpaiementecheance
self.echeances.where("date <= ?",Date.today).where.not(id: self.echeances.joins(:card).select("echeances.id"))
end
def echeancefuturnonpayes
self.echeances.where("date >= ?",Date.today).where.not(id: self.echeances.joins(:card).select("echeances.id"))
end
def echeancepassenonpayes
self.echeances.where("date < ?",Date.today).where.not(id: self.echeances.joins(:card).select("echeances.id"))
end

end

app/models/paymentcourse.rb
class Paymentcourse < ApplicationRecord
belongs_to :course
end

app/models/private.rb
class Private < Course
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  def self.myschedule
   all.select("schedules.*, row_number() over(order by schedules.id) as rownum").group(:id)
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :payments
  accepts_nested_attributes_for :payments, allow_destroy: true
  attr_accessor :terms
  attr_accessor :mytype
  validates :terms, acceptance: { message: "J'ai lu et j'accepte les conditions générales d'inscription." }
  belongs_to :level
  has_and_belongs_to_many :courses, :join_table => :userhascourses
  has_many :userweekdays
  has_many :weekdays, :through => :userweekdays
  accepts_nested_attributes_for :userweekdays, allow_destroy: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/userweekday.rb
class Userweekday < ApplicationRecord
  has_and_belongs_to_many :schedules, :join_table =>:houruserweekdays
belongs_to :user
belongs_to :weekday
end

app/models/webbillet.rb
class Webbillet < ApplicationRecord
def flyer=(uploaded_io)
File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
  file.write(uploaded_io.read)
end
write_attribute(:flyer, uploaded_io.original_filename)
end
def self.recent
order(:created_at => :desc)
end
def flyer
read_attribute(:flyer)
end
end

app/models/weekday.rb
class Weekday < ApplicationRecord
end

app/controllers/achats_controller.rb
class AchatsController < ApplicationController
  before_action :find_course, only:[:add, :show]
  def show
      
  end
    def add
        session[:achats]||={}
        
            session[:achats][params[:id]]=params[:quantite]
            total=session[:achats].to_a.map{|a,b|Course.find(a).price*b.to_i}.sum
            soustotal=params[:quantite].to_i * @course.price
        p session[:achats]    
        render json: {"soustotal"=>soustotal, sum: session[:achats].values.map(&:to_i).sum, total: total}, layout: false
    
    end
  def cours
    case params[:mytype]
    when "collectifs"
      @course=Collective.all
    when "individuels"
      @course=Private.all
    #else
    #  @course=Course.all
    end

  end
  private
  def find_course
    @course=Course.find(params[:id])
  end
end

app/helpers/achats_helper.rb
module AchatsHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/ifdm_helper.rb
module IfdmHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/webbillets_helper.rb
module WebbilletsHelper
end

app/views/achats/_cours.html.erb
  <div class="col achat">
<%=link_to achatscourspanier_path(id: course.id,mytype: params[:mytype]) do%>
    <div class="card">
      <img src="/uploads/<%=course.image%>" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title"><%=course.name%></h5>
        <p class="card-text"><%=number_to_currency(course.price,locale: :fr)%></p>
      </div>
    </div>
<%end%>
  </div>

app/views/achats/_course.html.erb
  <div class="col">
    <div class="card">
      <img src="/uploads/<%=course.image%>" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title"><%=course.name%></h5>
        <p class="card-text"><%=number_to_currency(course.price,locale: :fr)%></p>
      </div>
    </div>
  </div>

app/views/achats/_myoverlay.html.erb
<div id="overlay">
  <div id="text">

<div class="coursetitle"><span class="title">Produit ajouté au panier avec succès</span><span onclick="off()">X</span></div>

<div>
   <div class="card" style="width: 18rem;flex-direction:row;">
  <img src="/uploads/<%=course.image%>" class="card-img-top" style="width:30%;" alt="...">
  <div class="card-body">
    <h5 class="card-title"><%=course.mytitle%></h5>
    <p class="card-text myprice"><%=number_to_currency(course.price)%></p>
    <p class="card-text">Quantité : <span class="quantite"></span></p>
    <p class="card-text">
<a class="btn btn-light" href="" onclick="off();return false;" role="button">Continuer mes achats</a>
<a class="btn btn-primary" href="/order" role="button">Commander</a>

</p>
    
  


  </div>
</div>
      <div class="card" style="width: 18rem;flex-direction:row;">
  <div class="card-body">
      <p class="card-text myprice">Il y a <span class="sum"></span> articles das votre panier</p>
    <p class="card-text">Sous-total : <span class="soustotal"></span></p>
    <p class="card-text">Total : <span class="total"></span></p>
    
  


  </div>
</div>

    
</div>


</div>
</div>

app/views/achats/_showcourse.html.erb
<div class="card" style="width: 18rem;flex-direction:row;">
  <img src="/uploads/<%=course.image%>" class="card-img-top" style="width:30%;" alt="...">
  <div class="card-body">
    <h5 class="card-title"><%=course.mytitle%></h5>
    <p class="card-text myprice"><%=number_to_currency(course.price)%></p>
    <p class="card-text">Aucune taxe</p>
    <p class="card-text">Quantité<br>
<input type="number" name="numbercourse<%=course.id%>" id="numbercourse<%=course.id%>"/>
<a href="" class="btn btn-primary addtobasket" data-mytype="<%=params[:mytype]%>" data-id="<%=course.id%>">Ajouter au panier</a>
</p>
   <p class="card-text">Garanties sécurité Systempay<br>
certifiée PCI-DSS</p> 
<div>
<p class="details">
Détails du produit
</p>
<p>
Référence <%=course.mytitle.upcase%>
</p>
</div>

  </div>
</div>

app/views/achats/cours.html.erb
<main class="mesachats">
<div class="mybreadcrumb">
<span>
accueil
</span>
<span>
cours <%=params[:mytype]%>
</span>
</div>
<div class="achats">
<div class="mytitle">
cours <%=params[:mytype]%>
</div>
<div class="myachats">
<div class="title">
cours <%=params[:mytype]%>
</div>
</div>
<div class="row row-cols-1 row-cols-md-2 g-4">
<%=render collection: @course, as: :course, partial: "achats/cours"%>
</div>
</div>
</main>

app/views/achats/show.html.erb
<%=render "showcourse", course: @course%>
<%=render "myoverlay", course: @course%>