config/routes.rb
Rails.application.routes.draw do
  resources :cards
  get "paiementsucces", to: "order#paiementsuccess"
  get 'monpaiement', to: "order#monpaiement"
  get 'okorder', to: "order#okorder"
  get 'delete/:id', to: "order#deletemyaction"
  get 'order', to: "order#myorder"
  get 'order/myorder'
  get "inscriptions/success", to: "inscriptions#success", as: :moninscription
  get 'achats/cours'
  devise_scope :user do 
    patch "/okorder", to: "users/registrations#update", as: :editercollectifs_post
    post "/inscription-:mytype", to: "users/registrations#create", as: :inscriptioncollectifs_post
  end
  devise_for :users, controllers: { registrations: 'users/registrations',sessions: 'users/sessions'  }
  resources :courses
  get 'achats-cours-:mytype', to:"achats#cours", as: :achatscours
  get 'achats-cours-:mytype/:id/ajouteraupanier', to:"achats#show", as: :achatscourspanier
  get 'achats-cours-:mytype/:id/add', to:"achats#add", as: :achatsadd
  get 'inscriptions/index'
  resources :courses
  resources :webbillets
  get "/forminscriptions", to: "inscription#form", as: :inscriptionform
  get "/inscription-individuels", to: "inscriptions#individuels", as: :inscriptionindividuels
  get "/inscription-collectifs", to: "inscriptions#collectifs", as: :inscriptioncollectifs

  get "/cours-collectifs-de-:name", to: "courses#show", as: :noscourscollectifsde
  get "/cours-individuels-de-:name", to: "courses#show", as: :noscoursindividuelsde
  get "/nos-cours-:type", to: "courses#index"
  #get 'ifdm/index'
  #get 'contact/index'
  #get 'internships/index'
  #get 'courses/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "ifdm#index"
  get "ifdm", to: "ifdm#index"
  get "nos-cours-individuels", to: "courses#individual", as: :coursindividuel
  get "nos-cours-collectifs", to: "courses#group", as: :courscollectif
  get "nos-cours-:type", to: "courses#index", as: :allcourses
  get "nos-stages", to: "internships#index"
  get "nos-evenements", to: "events#index"
  get "contact-2", to: "contact#index"
end

app/models/webbillet.rb
class Webbillet < ApplicationRecord
def flyer=(uploaded_io)
File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
  file.write(uploaded_io.read)
end
write_attribute(:flyer, uploaded_io.original_filename)
end
def self.recent
order(:created_at => :desc)
end
def flyer
read_attribute(:flyer)
end
end

app/controllers/webbillets_controller.rb
class WebbilletsController < ApplicationController
  before_action :set_webbillet, only: %i[ show edit update destroy ]

  # GET /webbillets or /webbillets.json
  def index
    @webbillets = Webbillet.all
  end

  # GET /webbillets/1 or /webbillets/1.json
  def show
  end

  # GET /webbillets/new
  def new
    @webbillet = Webbillet.new
  end

  # GET /webbillets/1/edit
  def edit
  end

  # POST /webbillets or /webbillets.json
  def create
    @webbillet = Webbillet.new(webbillet_params)

    respond_to do |format|
      if @webbillet.save
        format.html { redirect_to webbillet_url(@webbillet), notice: "Webbillet was successfully created." }
        format.json { render :show, status: :created, location: @webbillet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @webbillet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /webbillets/1 or /webbillets/1.json
  def update
    respond_to do |format|
      if @webbillet.update(webbillet_params)
        format.html { redirect_to webbillet_url(@webbillet), notice: "Webbillet was successfully updated." }
        format.json { render :show, status: :ok, location: @webbillet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @webbillet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /webbillets/1 or /webbillets/1.json
  def destroy
    @webbillet.destroy

    respond_to do |format|
      format.html { redirect_to webbillets_url, notice: "Webbillet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_webbillet
      @webbillet = Webbillet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def webbillet_params
      params.require(:webbillet).permit(:flyer, :url, :title)
    end
end

app/helpers/webbillets_helper.rb
module WebbilletsHelper
end

app/views/webbillets/_form.html.erb
<%= form_with(model: webbillet, local: true) do |form| %>
  <% if webbillet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(webbillet.errors.count, "error") %> prohibited this webbillet from being saved:</h2>

      <ul>
        <% webbillet.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :flyer %>
    <%= form.file_field :flyer %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/webbillets/_webbillet.html.erb
<article class="billetweb">
<%=link_to webbillet.url do%>
<img src="/assets/<%=webbillet.flyer%>" alt="Flyer <%=webbillet.title%>"/>
<%end%>

<a href="<%=webbillet.url%>">
Achetez vos billets
</a>
<hr>

</article>

app/views/webbillets/edit.html.erb
<h1>Editing Webbillet</h1>

<%= render 'form', webbillet: @webbillet %>

<%= link_to 'Show', @webbillet %> |
<%= link_to 'Back', webbillets_path %>

app/views/webbillets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Webbillets</h1>

<table>
  <thead>
    <tr>
      <th>Flyer</th>
      <th>Url</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @webbillets.each do |webbillet| %>
      <tr>
        <td><%= webbillet.flyer %></td>
        <td><%= webbillet.url %></td>
        <td><%= webbillet.title %></td>
        <td><%= link_to 'Show', webbillet %></td>
        <td><%= link_to 'Edit', edit_webbillet_path(webbillet) %></td>
        <td><%= link_to 'Destroy', webbillet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Webbillet', new_webbillet_path %>

app/views/webbillets/new.html.erb
<h1>New Webbillet</h1>

<%= render 'form', webbillet: @webbillet %>

<%= link_to 'Back', webbillets_path %>

app/views/webbillets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Flyer:</strong>
  <%= @webbillet.flyer %>
</p>

<p>
  <strong>Url:</strong>
  <%= @webbillet.url %>
</p>

<p>
  <strong>Title:</strong>
  <%= @webbillet.title %>
</p>

<%= link_to 'Edit', edit_webbillet_path(@webbillet) %> |
<%= link_to 'Back', webbillets_path %>