config/routes.rb
Rails.application.routes.draw do
  resources :cards
  get "paiementsucces", to: "order#paiementsuccess"
  get 'monpaiement', to: "order#monpaiement"
  get 'okorder', to: "order#okorder"
  get 'delete/:id', to: "order#deletemyaction"
  get 'order', to: "order#myorder"
  get 'order/myorder'
  get "inscriptions/success", to: "inscriptions#success", as: :moninscription
  get 'achats/cours'
  devise_scope :user do 
    patch "/okorder", to: "users/registrations#update", as: :editercollectifs_post
    post "/inscription-:mytype", to: "users/registrations#create", as: :inscriptioncollectifs_post
  end
  devise_for :users, controllers: { registrations: 'users/registrations',sessions: 'users/sessions'  }
  resources :courses
  get 'achats-cours-:mytype', to:"achats#cours", as: :achatscours
  get 'achats-cours-:mytype/:id/ajouteraupanier', to:"achats#show", as: :achatscourspanier
  get 'achats-cours-:mytype/:id/add', to:"achats#add", as: :achatsadd
  get 'inscriptions/index'
  resources :courses
  resources :webbillets
  get "/forminscriptions", to: "inscription#form", as: :inscriptionform
  get "/inscription-individuels", to: "inscriptions#individuels", as: :inscriptionindividuels
  get "/inscription-collectifs", to: "inscriptions#collectifs", as: :inscriptioncollectifs

  get "/cours-collectifs-de-:name", to: "courses#show", as: :noscourscollectifsde
  get "/cours-individuels-de-:name", to: "courses#show", as: :noscoursindividuelsde
  get "/nos-cours-:type", to: "courses#index"
  #get 'ifdm/index'
  #get 'contact/index'
  #get 'internships/index'
  #get 'courses/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "ifdm#index"
  get "ifdm", to: "ifdm#index"
  get "nos-cours-individuels", to: "courses#individual", as: :coursindividuel
  get "nos-cours-collectifs", to: "courses#group", as: :courscollectif
  get "nos-cours-:type", to: "courses#index", as: :allcourses
  get "nos-stages", to: "internships#index"
  get "nos-evenements", to: "events#index"
  get "contact-2", to: "contact#index"
end

app/models/card.rb
class Card < ApplicationRecord
belongs_to :payment
belongs_to :echeance, optional: true
before_save :mygmt
after_validation :addmyerror
def mypaymentcreated
j=self.gmt >= 0 ? "+" : ""
j<<self.gmt.to_s
(self.created_at+self.gmt.hours).to_datetime.change(offset: j)
end
def mygmt
self.gmt=Time.now.getlocal.strftime("%:z").to_i
end
def addmyerror
if self.payment.cards.length >= self.payment.option.to_i
self.errors.add(:myerror,"vous avez payé toute les échéances")
end
    if self.payment.echeancepassenonpayes.length > 0
self.errors.add(:myerror,"vous avez râté des échéances.contactez l'école")
 
   end
    if self.payment.echeancefuturnonpayes.length == 0
self.errors.add(:myerror,"vous avez payé toute les échéances")

    end
end
def mycardnumber
d=nb
d[0..-4]="x" * d[0..-4].length
d
end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  protect_from_forgery except: [:create]
  before_action :set_card, only: %i[ show edit update destroy ]

  # GET /cards or /cards.json
  def index
    @cards = Card.all
  end

  # GET /cards/1 or /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards or /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to card_url(@card), notice: "Card was successfully created." }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1 or /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to card_url(@card), notice: "Card was successfully updated." }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1 or /cards/1.json
  def destroy
    @card.destroy

    respond_to do |format|
      format.html { redirect_to cards_url, notice: "Card was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def card_params
      params.require(:card).permit(:nb, :expire, :cvc, :sum, :payment_id,:echeance_id)
    end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_form.html.erb
<h2>Informations pour le paiement</h2>
<%= form_with(model: card, local: true,html:{id:"payment-form"}) do |form| %>
  <% if card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
        <% card.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-row">
    <div class="form-group col-md-6">
    <%= form.label :nb %>
    <%= form.text_field :nb,class:"form-control" %>
  </div>
  </div>

  <div class="form-row">
    <div class="form-group col-md-6">
    <%= form.label :expire %>
    <%= form.date_select("expire", order: [:month, :year]) %>
  </div>
  </div>

  <div class="form-row">
    <div class="form-group col-md-6">
    <%= form.label :cvc %>
    <%= form.text_field :cvc,class:"form-control" %>
  </div>
  </div>

    <%= form.hidden_field :sum %>
    <%= form.hidden_field :payment_id %>
    <%= form.hidden_field :echeance_id %>

  <div class="actions">
    <%= form.submit :valider, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cards</h1>

<table>
  <thead>
    <tr>
      <th>Nb</th>
      <th>Expire</th>
      <th>Cvc</th>
      <th>Sum</th>
      <th>Payment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cards.each do |card| %>
      <tr>
        <td><%= card.nb %></td>
        <td><%= card.expire %></td>
        <td><%= card.cvc %></td>
        <td><%= card.sum %></td>
        <td><%= card.payment_id %></td>
        <td><%= link_to 'Show', card %></td>
        <td><%= link_to 'Edit', edit_card_path(card) %></td>
        <td><%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Card', new_card_path %>

app/views/cards/new.html.erb
<h1>New Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nb:</strong>
  <%= @card.nb %>
</p>

<p>
  <strong>Expire:</strong>
  <%= @card.expire %>
</p>

<p>
  <strong>Cvc:</strong>
  <%= @card.cvc %>
</p>

<p>
  <strong>Sum:</strong>
  <%= @card.sum %>
</p>

<p>
  <strong>Payment:</strong>
  <%= @card.payment_id %>
</p>

<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>